@startuml
class com.developsunghyun.iot_linker.Model.Data.DBItemData {
}
class com.developsunghyun.iot_linker.Model.Data.WidgetData {
}
interface com.developsunghyun.iot_linker.Model.Data.ItemDao {
+ void insert(DBItemData)
+ void update(DBItemData)
+ void delete(DBItemData)
+ Flow<DBItemData> getItem(Int)
+ Flow<List<DBItemData>> getAllItems()
}

class com.developsunghyun.iot_linker.View.LayoutPrint {
- List<Map<String, @Composable () -> Unit>> widgetList
- Map<String,  @Composable (@Composable () -> Unit) -> Unit> layout2Slot
+ void null()
+ void null()
+ void null()
+ void null()
+ void null()
+ void PreView()
}


class com.developsunghyun.iot_linker.Model.Data.InterfaceLayoutData {
}
class com.developsunghyun.iot_linker.Model.Repository.DataBase$Companion {
- DataBase? Instance
+ DataBase getDatabase(Context)
}


abstract class com.developsunghyun.iot_linker.Model.Repository.DataBase {
+ ItemDao dbItemDao()
}

class com.developsunghyun.iot_linker.MainActivity {
+ void onCreate(Bundle?)
}

class com.developsunghyun.iot_linker.Model.Data.WidgetsData {
}
class com.developsunghyun.iot_linker.ViewModel.CreateViewModel {
-  _layoutData
+ State<LayoutItem> layoutData
+ void setLayoutType(String)
+ void setSlitNumber(Int)
+ void setModuleArray(Int,String)
}


class com.developsunghyun.iot_linker.Model.Repository.LocalDataRepository {
+  dbContext
+  dao
+ void testInsert()
+ LiveData<DBItemData> getData()
}


class com.developsunghyun.iot_linker.Model.Data.LayoutDataList {
+ List<InterfaceLayoutData> layoutListData
}

class com.developsunghyun.iot_linker.View.Screen.NavigationItem {
}
class com.developsunghyun.iot_linker.Model.Data.LayoutItem {
}


com.developsunghyun.iot_linker.Model.Repository.DataBase +.. com.developsunghyun.iot_linker.Model.Repository.DataBase$Companion
androidx.room.RoomDatabase <|-- com.developsunghyun.iot_linker.Model.Repository.DataBase
androidx.activity.ComponentActivity <|-- com.developsunghyun.iot_linker.MainActivity
androidx.lifecycle.ViewModel <|-- com.developsunghyun.iot_linker.ViewModel.CreateViewModel
@enduml